# Generated by Django 4.1.4 on 2022-12-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='Card Resimi'),
        ),
    ]
