# Generated by Django 4.1.4 on 2022-12-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_category_card_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='priece',
            field=models.IntegerField(null=True, verbose_name='Ürün Fiyatı'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Paylaşım Zamanı'),
        ),
    ]
