# Generated by Django 4.1.4 on 2022-12-16 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.card', verbose_name='Ürünler'),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_now',
            field=models.DateTimeField(null=True, verbose_name='Yorum Zamanı'),
        ),
    ]
