# Generated by Django 4.1.4 on 2022-12-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0008_card_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image1',
            field=models.FileField(null=True, upload_to='', verbose_name='Card Resimi 2'),
        ),
        migrations.AddField(
            model_name='card',
            name='image2',
            field=models.FileField(null=True, upload_to='', verbose_name='Card Resimi 3'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='Card Resimi 1'),
        ),
    ]
