# Generated by Django 4.1.4 on 2022-12-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_remove_card_image_card_image3_alter_card_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Profil'),
        ),
    ]
